project:
  type: website
  output-dir: docs
  
website:
  title: "William Smithers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/wsmithers
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, William Smithers"

format:
  html:
    theme: cerulean
    toc: true

editor: source

