project:
  type: website
  output-dir: docs
  
website:
  title: "William Smithers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
    tools:
      - icon: github
        href: https://github.com/wsmithers
      - icon: linkedin
        href: https://www.linkedin.com/in/willsmithers/
  page-footer:
    right: "Built with <3 on the [Central Coast](https://www.slocal.com/)"
    left: "&copy; Copyright 2023, William Smithers"

format:
  html:
    theme: litera
    toc: true

editor: source

