---
title: "Projects"
layout: blog
---

# My Projects

Welcome to my projects page! Here, you will find a collection of my recent legal and statistical research.

## Project 2: *[IN PROGRESS]* Proposal to Reform the California Franchise Tax Board’s Filing Enforcement Procedures for Individuals with Occupational Licenses under Revenue and Taxation Code (RTC) § 19087

**Date:** January 2025

**Description:** My research critically examines the California Franchise Tax Board’s (FTB) practice of assessing income against individuals holding professional licenses, even in cases where no earnings were reported. Under California Revenue and Taxation Code § 19087, the FTB presumes income based solely on licensure status, often leading to aggressive tax enforcement actions such as wage garnishments and bank levies. This study explores the statutory origins of this policy, its due process and fairness implications, and the broader economic consequences for affected professionals. Additionally, I conduct a comparative analysis of similar statutes in five other states, highlighting key differences in tax enforcement strategies. By addressing these issues, my work aims to contribute to legal scholarship on occupational taxation and advocate for policy reforms that ensure equitable treatment of license holders under the law.

**Tags:** Tax, Law, Business Law, California, FTB


## Project 1: Analysis of US Crime Rates

**Date:** 2023-11-15

**Description:** Check out my latest project for STAT331 at CalPoly! In this project, my collegues and I statistically analyze US crime rates on the national, regional, and municipal level. We connect these findings to the crime rates in San Luis Obispo.

**Tags:** R, Data Analysis, Crime

**Link:** [Read more](https://wsmithers.github.io/projd1_backup.html)
**Shiny App:** [Launch App](https://celest.shinyapps.io/crime_rate_shiny_app/)